"""Constants and limits."""

TELEGRAM_MESSAGE_LIMIT = 4096
TOC_MAX_LENGTH = 4000
TOC_GROUPS_COUNT = 5
TOC_POSTS_PER_GROUP = 7
TOC_POSTS_PERIOD_DAYS = 365
POSTS_PER_PAGE = 10
TOPICS_PER_PAGE = 8
MAX_DESCRIPTION_LENGTH = 50
MAX_POST_TEXT_FOR_LLM = 1500

# Scoring weights
SCORE_ENGAGEMENT_WEIGHT = 0.4
SCORE_FRESHNESS_WEIGHT = 0.3
SCORE_USEFULNESS_WEIGHT = 0.3
# KEEP IN SYNC WITH ct_recalculate_channel_scores() in schema.sql (currently hardcodes 180.0).
FRESHNESS_HALF_LIFE_DAYS = 180

# TOC regeneration thresholds — gate the expensive Gemini call in process_channel().
# Both conditions must be met to regenerate; first run (toc_updated_at IS NULL) bypasses.
TOC_REGEN_MIN_HOURS = 24
TOC_REGEN_MIN_NEW_CLASSIFIED = 5

# Fetcher
FETCH_DELAY_SECONDS = 2

# Digest
DIGEST_INTERVAL_HOURS = 3
DIGEST_MAX_POSTS_PER_CHANNEL = 20
DIGEST_MESSAGE_MAX_LENGTH = 4000
DIGEST_MAX_POST_TEXT = 1500
