"""Constants and limits."""

TELEGRAM_MESSAGE_LIMIT = 4096
TOC_TARGET_LENGTH = 1000
TOC_MAX_LENGTH = 2000
POSTS_PER_PAGE = 10
TOPICS_PER_PAGE = 8
MAX_DESCRIPTION_LENGTH = 80
MAX_POST_TEXT_FOR_LLM = 1500

# Scoring weights
SCORE_ENGAGEMENT_WEIGHT = 0.4
SCORE_FRESHNESS_WEIGHT = 0.3
SCORE_USEFULNESS_WEIGHT = 0.3
FRESHNESS_HALF_LIFE_DAYS = 180
